version: '2'
services:

  php:
    image: php:apache
    container_name: lamp_php7_apache
    restart: always
    volumes:
      - ./html/:/var/www/html
    ports:
      - 80:80

  db:
    image: mariadb:latest
    container_name: lamp_mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD:db_123db2123
      - MYSQL_DATABASE=lamp_db
      - MYSQL_USER=lamp
      - MYSQL_PASSWORD=_123db456
